print("Set")
my_set = set()
my_set.add(2)
my_set.add(3)
my_set.add(5)
my_set.add(7)
print(my_set)
my_set.add(1)
print(my_set)
my_set.remove(1)
print(3 in my_set)
print(4 in my_set)
my_set.add(3)
print(my_set)
#  my_set2 = set([7, 11, 13, 17])
my_set2 = [7, 11, 13, 17]
print(my_set | my_set2)
print(my_set & my_set2)
print(my_set - my_set2)
my_set3 = {2, 3, 3, 5, 5, 7}
print(my_set3)
